# Generated by Django 4.1.3 on 2023-09-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flipkart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrations", old_name="last", new_name="last_name",
        ),
    ]
