# Generated by Django 4.1.3 on 2023-09-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flipkart", "0002_rename_last_registrations_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("category_image", models.ImageField(upload_to="upload/category/")),
            ],
        ),
    ]
